#' Attach a full model to the tibble of model terms
#'
#' To facilitate the use of broom helpers with pipe, it is recommended to
#' attach the original model as an attribute to the tibble of model terms
#' generated by `broom::tidy()`.
#'
#' `tidy_attach_model()` attach the model to a tibble already generated while
#' `tidy_and_attach()` will apply `broom::tidy()` and attach the model.
#'
#' Use `tidy_get_model()` to get the model attached to the tibble and
#' `tidy_detach_model()` to remove the attribute containing the model.
#' @param model a model to be attached/tidied
#' @param x a tibble of model terms
#' @param tidy_fun option to specify a custom tidier function
#' @param exponentiate logical indicating whether or not to exponentiate the
#' coefficient estimates. This is typical for logistic, Poisson and Cox models,
#' but a bad idea if there is no log or logit link; defaults to `FALSE`
#' @param .attributes named list of additional attributes to be attached to `x`
#' @param ... other arguments passed to `tidy_fun()`
#' @family tidy_helpers
#' @examples
#' mod <- lm(Sepal.Length ~ Sepal.Width + Species, data = iris)
#' tt <- mod %>%
#'   tidy_and_attach(conf.int = TRUE)
#' tt
#' tidy_get_model(tt)
#' @export
tidy_attach_model <- function(x, model, .attributes = NULL) {
  attr(x, "model") <- model
  for (a in names(.attributes)) {
    if (!is.null(.attributes[[a]]))
      attr(x, a) <- .attributes[[a]]
  }
  x
}

#' @rdname tidy_attach_model
#' @export
tidy_and_attach <- function(model, tidy_fun = broom::tidy, exponentiate = FALSE, ...) {
  # test if exponentiate can be passed to tidy_fun
  tryCatch(
    tidy_fun(model, exponentiate = exponentiate, ...) %>%
      tidy_attach_model(model, .attributes = list(exponentiate = exponentiate)),
    error = function(e) {
      if (exponentiate)
        stop("`exponentiate = TRUE` is not valid for this type of model.")
      tidy_fun(model, ...) %>%
        tidy_attach_model(model, .attributes = list(exponentiate = FALSE))
    }
  )



}

#' @rdname tidy_attach_model
#' @export
tidy_get_model <- function(x) {
  attr(x, "model")
}

#' @rdname tidy_attach_model
#' @export
tidy_detach_model <- function(x) {
  attr(x, "model") <- NULL
  x
}
